export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>RefinkAppBuyerV2</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/png" href="assets/logo-home.png">

<style>html,body{height:100%;margin:0;padding:0}body{min-height:100%}@media (min-width:768px){html{display:flex;justify-content:center;height:100%;width:100%;background-color:#000;margin:0;padding:0}app-root,app-register{display:block;width:100%;height:100%}body{height:100%;width:70%;background-color:#fff;margin:0;padding:0}}@media (min-width:1040px){html{display:flex;justify-content:center;height:120%;width:100%;background-color:#000}body{font-family:sans-serif;width:80%;background-color:#fff}}
</style><link rel="stylesheet" href="styles-K3A7TUK3.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-K3A7TUK3.css"></noscript><style ng-app-id="ng">header[_ngcontent-ng-c4169353346]{flex-direction:row;color:#fff;background-color:#f5f5f5;height:4.5rem;display:flex;justify-content:space-between;align-items:center;padding-left:1rem;padding-right:1rem}img[_ngcontent-ng-c4169353346]{width:8rem;height:8rem;background-position:center;background-size:100%;background-repeat:no-repeat}.register[_ngcontent-ng-c4169353346]{justify-self:center;border:1px solid #a9c6c3;margin-top:5%;display:flex;align-items:center;flex-direction:column;width:80%;border-radius:10px}form[_ngcontent-ng-c4169353346]{display:flex;justify-content:center;align-items:center;flex-direction:column;width:100%}h2[_ngcontent-ng-c4169353346]{color:#083c3a}input[_ngcontent-ng-c4169353346]{margin-top:3%;height:1.5rem;width:70%}.error[_ngcontent-ng-c4169353346]{color:red;font-weight:700}#registerButton[_ngcontent-ng-c4169353346]{background-color:#4891e4;margin-top:3%;color:#fff;border:none;border-radius:20px;width:70%;height:2rem}#alreadyAccount[_ngcontent-ng-c4169353346]{background-color:#fff;border:none;color:#6ea8eb;padding-bottom:2%}@media (min-width:768px){.register[_ngcontent-ng-c4169353346], #registerButton[_ngcontent-ng-c4169353346]{width:60%}}@media (min-width:1040px){.register[_ngcontent-ng-c4169353346], #registerButton[_ngcontent-ng-c4169353346]{width:30%}}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["submit","input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="20.2.4" ngh="1" ng-server-context="ssg"><router-outlet></router-outlet><app-register _nghost-ng-c4169353346 ngh="0"><header _ngcontent-ng-c4169353346><img _ngcontent-ng-c4169353346 src="/assets/logo.png" alt="Logo" class="logo-header"></header><div _ngcontent-ng-c4169353346 class="register"><h2 _ngcontent-ng-c4169353346>Inscription</h2><form _ngcontent-ng-c4169353346 novalidate class="ng-untouched ng-pristine ng-invalid" jsaction="submit:;"><input _ngcontent-ng-c4169353346 type="text" formcontrolname="firstName" placeholder="Prénom" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="text" formcontrolname="lastName" placeholder="Nom" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="email" formcontrolname="emailAddress" placeholder="Adresse email" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="text" formcontrolname="city" placeholder="Ville" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="tel" formcontrolname="phoneNumber" placeholder="Numéro de téléphone" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="number" formcontrolname="postalCode" placeholder="Code postal" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><input _ngcontent-ng-c4169353346 type="password" formcontrolname="password" placeholder="Mot de passe" value class="ng-untouched ng-pristine ng-invalid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c4169353346 class="error"><!----></div><button _ngcontent-ng-c4169353346 id="registerButton" type="submit" disabled>S'inscrire</button></form><p _ngcontent-ng-c4169353346 class="alert"><!--ngetn--></p><button _ngcontent-ng-c4169353346 id="alreadyAccount" routerlink="/login" tabindex="0" jsaction="click:;">Déjà inscrit ? Cliquez ici</button></div></app-register><!----></app-root>
<script src="polyfills-5CFQRCPP.js" type="module"></script><script src="main-HQVYK5DC.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"8":"t0","11":"t1","14":"t2","17":"t3","20":"t4","23":"t5","26":"t6"},"c":{"8":[],"11":[],"14":[],"17":[],"20":[],"23":[],"26":[]}},{"c":{"0":[{"i":"c4169353346","r":1}]}}]}</script></body></html>`;